### ISSUE TITLE
Linux compatibility

### ISSUE THREAD

**Issue by Demellion** [TheMysteriousVincent/ArmA3URLFetch#27]
Hi there, we've encountered a lot of reports that extension fails to load on Linux version of dedicated server. Reports origin from **Ubuntu 16.04**, **Debian 9.5.0** and sometimes other linux systems. We've checked that **ldd** reports all dependencies to be in place on the same OS.
Might it be so some of the libs doesn't support specific OS, and if they do - what types of OS are currently 100% supported?
Thanks.

**Comment by pixlcrashr** [comment]
Hi. Would you like to upload your server log file aswell as your ldd results on the `arma3urlfetch.so` lib?
And would you like to name the used version of ArmA3URLFetch?

**Comment by Demellion** [comment]
1. Version: 1.0
2. ldd: https://hastebin.com/anaqicoduk.php
3. Couldn't get the particular user rpt, but it reports all the same as it's not found
` Call extension 'arma3urlfetch' could not be found`

We did place it properly and know how it works, since using it massively in Windows version. Passed `chmod` and permissions in general. Tried `775` and `777`. It seems like it simply cannot be executed by Arma server. We could try to debug it, but since it's not detected at all - we can't get any verbose.

**Comment by pixlcrashr** [comment]
Thanks for your logs. I was able (and am) to reproduce this error on the last version.
The bad thing is that A3 has no way to output more information why this error occurs...

I have to say that I had to (and have to for now) go back to 171ad49b5c2d8d4e13d643a61e6477ea1ea6f256 and check whether there was a such an issue. There was none. Now, I'm currently checking what causes this denying of the library.

Hopefully it is just a Makefile/compiler command mistake.

**Comment by Demellion** [comment]
Thank you for addressing the issue, we'll stay tuned for updates.

**Comment by pixlcrashr** [comment]
I guess I have found the error. Probably the dynamic library was not able to link against(?) the static libraries `libcurl`, `libssl` and `libcrypto` because they were addressed at the linker before the source code. An example:
```Makefile
link:
        @$(CXX) $(LIBS) $(OBJS) $(LDFLAGS) -ldl -o $(OUTPUT)
```
, which instead should be:
```Makefile
link:
        @$(CXX) $(OBJS) $(LIBS) $(LDFLAGS) -ldl -o $(OUTPUT)
```

Nevertheless, the next update is coming in the next one or two days, since I currently only have to fix the quoting of strings of `#jsonToArray`.

(Should be) fixed with ff3e00a49a3264aa24ee1a0578762173d5c13698

Until the next update you can use the attached binary:
[arma3urlfetch.zip](https://github.com/playnet-public/ArmA3URLFetch/files/2713377/arma3urlfetch.zip)

Have a great evening!

**Comment by VeratoxMC** [comment]
Still not working :/, same error as before.

`Call extension 'arma3urlfetch' could not be loaded`


OS:
`Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
`

**Comment by pixlcrashr** [comment]
Well. I just tested compiling on an Ubuntu machine and it worked fine as expected. The main problem is that I temporarily have to differentiate between Ubuntu and Debian binaries.
It is the fact that the current building uses distribution-specific `libssl` and `libcrypto` libraries - I guess.

So. Here is now a second binary for Ubuntu. Please reply if it works.
[arma3urlfetch.zip](https://github.com/playnet-public/ArmA3URLFetch/files/2713511/arma3urlfetch.zip)

**Comment by pixlcrashr** [comment]
#28

**Comment by VeratoxMC** [comment]
It works now, thank you very much

**Comment by VeratoxMC** [comment]
nvm, this is the Error i get:

https://pastebin.com/PajykQn0

**Comment by pixlcrashr** [comment]
You mean the segmentation fault?
Are you sure that this is caused by a3uf?

**Comment by Demellion** [comment]
> You mean the segmentation fault?
> Are you sure that this is caused by a3uf?

I can confirm that segfault happening around the second binary for Ubuntu. But I might blame exactly Arma this time. We should continue investigating this case.

**Comment by pixlcrashr** [comment]
I can confirm that this might cohere with A3UF. I was able to reproduce this error frequently. It is caused by the compilation of `libcurl` because it depends on specific compiled libraries `libssl` and `libcrypto`.
Thus, the Makefile of this mod has to contain the compilation process of `openssl`.

**Comment by VeratoxMC** [comment]
So, i need to wait for a new update? ^^

**Comment by pixlcrashr** [comment]
Give me a second (or two) to make fixes to the Makefile and the dependencies of the binary. Then I can give you guys a new (and working :) ) version of ArmA3URLFetch.

**Comment by pixlcrashr** [comment]
There you go! Let me hear if it works.
[arma3urlfetch.zip](https://github.com/playnet-public/ArmA3URLFetch/files/2715066/arma3urlfetch.zip)

**Comment by Demellion** [comment]
We've checked that A3UF now initializing but met some different issues, there is a full log from a different OS types. It seems to be that `https://` format URL is not properly passed in Linux strings. We gonna continue investigation on that case.

https://hastebin.com/hajuyosuna.php

**Comment by pixlcrashr** [comment]
@Demellion Ooops, my fault. I forget to tell you that I made changes on how to fetch a request with the new binary.
See [fn_request.sqf](https://github.com/playnet-public/ArmA3URLFetch/blob/master/%40ArmA3URLFetch/addons/common/functions/fn_request.sqf) for reference.

**Comment by pixlcrashr** [comment]
The next update include those changes, JFYI.

EDIT:
That is, because it is necessary that the HTTP status code is returned in some way. So I had to edit the library status codes.

**Comment by pixlcrashr** [comment]
One (important) thing, I noticed in your logs, is the ability to resolve redirects from the HTTP server.
With your server binary you are able to resolve those redirects with the `callExtension` parameter `#redirect`.

**Comment by pixlcrashr** [comment]
To make clearance on the topic of the current result codes, I added an explanation of them:
[CallExtension return code's](https://github.com/playnet-public/ArmA3URLFetch/wiki/CallExtension-return-code's)

**Comment by pixlcrashr** [comment]
JFYI the latest automatic build is available here:
https://circleci.com/gh/playnet-public/ArmA3URLFetch/36#artifacts/containers/0

**Comment by Demellion** [comment]
One question around this. So this build is only Ubuntu-wise?

**Comment by pixlcrashr** [comment]
No. There is also a Debian build process.
https://circleci.com/gh/playnet-public/ArmA3URLFetch/57

But I guess, since the OpenSSL libraries are build custom-wise, it does not matter where it is compiled.

But does it work, though?

**Comment by Demellion** [comment]
Sorry for long response, seem to be fine now. Can you please build Windows versions one under the same branch of changes towards 1.1, so we don't script HTTP responses in different script for linux, thanks. We don't expect it to be BE compatible, since we use it on server side only.

**Comment by pixlcrashr** [comment]
Of course I will build it. Also, if you check the CI's of the latest commits, you can download commit artifacts for Windows from the AppVeyor CI.

**Comment by pixlcrashr** [comment]
@Demellion @VeratoxMC JFYI There was a new release of ArmA3URLFetch https://github.com/playnet-public/ArmA3URLFetch/releases/tag/1.1

🎉 Happy New Year! 🎉
